SPOTIPY_CLIENT_ID: '0a774d28df90456996f936715bf7276b'
SPOTIPY_CLIENT_SECRET: 'a79977fd36c54f189635fe87ac6443ac'
SPOTIPY_REDIRECT_URI: 'http://localhost:5000'
SESSION_TYPE: 'filesystem'
SESSION_FILE_DIR: './.flask_session/'
PORT: 5000
LOGGING_LEVEL: 'INFO'