SPOTIPY_CLIENT_ID: '88eec4f7753e4dfca4df81e895266679'
SPOTIPY_CLIENT_SECRET: '23952bdbe81c4618b3950b4bf321da2b'
SPOTIPY_REDIRECT_URI: 'http://localhost:5000'
SESSION_TYPE: 'filesystem'
SESSION_FILE_DIR: './.flask_session/'
PORT: 5001
LOGGING_LEVEL: 'INFO'